packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/useGroupChannelMessagesWithCollection.ts
packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
packages/uikit-react-native/src/components/ChannelInput/index.tsx
packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageFocusAnimation.tsx
packages/uikit-react-native/src/components/GroupChannelMessageRenderer/index.tsx
packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelInput.tsx
packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelMessageList.tsx
packages/uikit-react-native/src/domain/groupChannel/module/moduleContext.tsx
packages/uikit-react-native/src/domain/groupChannel/types.ts
packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx

[UIKIT-4240]
- Implement scroll to parent message
- Implement send reply messages
- Add placeholder ui (message > parent message)
- Add placeholder ui (input > parent message preview)
- Add marks for message bottom sheet items
- reply
- delete
[UIKIT-4240]: https://sendbird.atlassian.net/browse/UIKIT-4240?atlOrigin=eyJpIjoiN …

feat(UIKIT-4240): implement basic quote reply logic

---

packages/uikit-chat-hooks/src/__tests__/channel/useChannelMessagesReducer.test.ts
packages/uikit-chat-hooks/src/channel/useChannelMessagesReducer.ts
packages/uikit-testing-tools/src/mocks/createMockMessage.ts

[CLNP-630]
현재 메세지 리스트는 오브젝트 형태로 관리하고 있습니다.
```ts
{
[outgoingMessage.reqId]: BaseMessage;
[incomingMessage.messageId]: BaseMessage;
}
```
원래 전송된 메세지는 messageId, 전송안된 메세지는 reqId 를 키로 사용하다가
내가 전송한 메세지는 모두 reqId 를 사용하도록 변경했고
이렇게 변경한 이유는 아래 케이스를 처리 하기 위함이었는데요
1. pending (messageRequestHandler)
2. succeeded (messageRequestHandler)
3. pending (collectionHandler)
4. succeeded (collectionHandler)
이미 내가 전송한 메세지가 succeeded 된 상태에서, pending message 업데이트가 들어올 경우
reqId 로 오브젝트에서 prev 메세지를 찾아서  `sendingStatus` 를 체크하기 위함이었습니다.
그런데 `channel.updateUserMessage` 와 같은 메소드로, 메세지를 업데이트 할 경우 `reqId` 가 변경됩니다.
업데이트 된 메세지의 새로운 reqId 는 오브젝트에 없기 때문에, 중복된 메세지로 추가되는 이슈가 있었습니다.
이를 방지하기 위해서 아래처럼 outgoingMessage 의 messageId 도 추가 하여
reqId/mesageId 로 오브젝트에서 prev 메세지를 찾도록 변경하고
메세지 리스트 오브젝트를 배열로 변경하여 반환할때는, 중복을 제거하는 처리를 추가했습니다. …

fix(CLNP-630): duplicated messages

---

packages/uikit-react-native/src/components/ChatFlatList/index.tsx

[CLNP-906]
Update inverted FlatList warning
- https://github.com/facebook/react-native/releases/tag/v0.72.4
- https://github.com/facebook/react-native/pull/38071
[CLNP-906]: https://sendbird.atlassian.net/browse/CLNP-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(CLNP-906): inverted flatlist android warning

---

packages/uikit-react-native/src/hooks/useMentionSuggestion.ts

[CLNP-1100]
[CLNP-1100]: https://sendbird.atlassian.net/browse/CLNP-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CLNP-1100): filter deactivated users when making mention suggestions

---

packages/uikit-react-native/src/components/ReactionBottomSheets/ReactionUserListBottomSheet.tsx
packages/uikit-react-native/src/components/ReactionBottomSheets/index.tsx
packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
packages/uikit-react-native/src/contexts/ReactionCtx.tsx

[CLNP-1147]
- **Add a `reaction.onPressUserProfile` to SendbirdUIKitContainer props**
onPress handler for below area<br/>
[CLNP-1147]: https://sendbird.atlassian.net/browse/CLNP-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CLNP-1147): add reaction.onPressUserProfile to SendbirdUIKitContainer props

---

packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx

[CLNP-1385]
- Add chat init params to SendbirdUIKitContainer chatOptions
[CLNP-1385]: https://sendbird.atlassian.net/browse/CLNP-1385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CLNP-1385): chat init params

---

packages/uikit-react-native/src/__tests__/utils/promise.test.ts
packages/uikit-react-native/src/index.ts
packages/uikit-react-native/src/utils/promise.ts

[CLNP-1564]
- Add `Promise.allSettled` polyfill for hermes environment.
[CLNP-1564]: https://sendbird.atlassian.net/browse/CLNP-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CLNP-1564): add promise polyfill for hermes

---

docs-validation/package.json
package.json
packages/uikit-chat-hooks/src/channel/useChannelMessagesReducer.ts
packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/index.ts
packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/useGroupChannelMessagesWithQuery.ts
packages/uikit-chat-hooks/src/channel/useOpenChannelMessages/useOpenChannelMessagesWithQuery.ts
packages/uikit-chat-hooks/src/types.ts
packages/uikit-react-native/package.json
packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
packages/uikit-react-native/src/components/ReactionAddons/BottomSheetReactionAddon.tsx
packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelMessageList.tsx
packages/uikit-react-native/src/domain/groupChannel/types.ts
packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
packages/uikit-testing-tools/src/mocks/createMockChannel.ts
packages/uikit-testing-tools/src/mocks/createMockGroupChannelCollection.ts
packages/uikit-testing-tools/src/mocks/createMockMessage.ts
packages/uikit-testing-tools/src/mocks/createMockMessageCollection.ts
packages/uikit-testing-tools/src/mocks/createMockQuery.ts
packages/uikit-testing-tools/src/mocks/createMockSendbirdSDK.ts
packages/uikit-testing-tools/src/mocks/createMockUser.ts
packages/uikit-utils/package.json
sample/package.json
yarn.lock

[CLNP-2051]
[CLNP-2051]: https://sendbird.atlassian.net/browse/CLNP-2051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(CLNP-2051): replaced useGroupChannelMessages

---

packages/uikit-react-native/src/components/ChannelInput/index.tsx
packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
packages/uikit-react-native/src/types.ts

fix: use ComponentType instead of function structure in CommonComponent type

---

packages/uikit-chat-hooks/src/channel/useGroupChannelList/index.ts
packages/uikit-chat-hooks/src/types.ts
packages/uikit-react-native/__template__/types.ts
packages/uikit-react-native/src/domain/groupChannel/types.ts
packages/uikit-react-native/src/domain/groupChannelBannedUsers/types.ts
packages/uikit-react-native/src/domain/groupChannelList/types.ts
packages/uikit-react-native/src/domain/groupChannelModeration/types.ts
packages/uikit-react-native/src/domain/groupChannelMutedMembers/types.ts
packages/uikit-react-native/src/domain/groupChannelNotifications/types.ts
packages/uikit-react-native/src/domain/groupChannelOperators/types.ts
packages/uikit-react-native/src/domain/groupChannelSettings/types.ts
packages/uikit-react-native/src/domain/groupChannelUserList/types.ts
packages/uikit-react-native/src/domain/messageSearch/types.ts
packages/uikit-react-native/src/domain/openChannel/types.ts
packages/uikit-react-native/src/domain/openChannelBannedUsers/types.ts
packages/uikit-react-native/src/domain/openChannelCreate/types.ts
packages/uikit-react-native/src/domain/openChannelList/types.ts
packages/uikit-react-native/src/domain/openChannelModeration/types.ts
packages/uikit-react-native/src/domain/openChannelMutedParticipants/types.ts
packages/uikit-react-native/src/domain/openChannelOperators/types.ts
packages/uikit-react-native/src/domain/openChannelSettings/types.ts
packages/uikit-react-native/src/domain/openChannelUserList/types.ts
packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
packages/uikit-react-native/src/fragments/createGroupChannelListFragment.tsx
sample/src/screens/uikit/groupChannel/GroupChannelScreen.tsx
sample/src/screens/uikit/groupChannel/GroupChannelTabs/GroupChannelListScreen.tsx

[CLNP-2179]
- Add `messageListQueryParams` to `GroupChannelFragment`.
- Add `channelListQueryParams` to `GroupChannelListFragment`.
- Deprecate the `collectionCreator` prop from `GroupChannelFragment` and `GroupChannelListFragment`.
- Deprecate the use of `useGroupChannelList` in `uikit-chat-hooks`.
- Fix Fragment types for finding the correct props place in the IDE.
What types of changes does your code introduce to this …

chore(CLNP-2179): introduced new list query params

---

package.json
packages/uikit-react-native-foundation/src/components/Image/Image.fastimage.tsx
packages/uikit-react-native-foundation/src/components/Image/index.ts
yarn.lock

[CLNP-2540]
---
```ts
import { Image } from '@sendbird/uikit-react-native-foundation';
// If you don't want to use FastImage in UIKit for React Native, you can specify this default prop
if (Image.defaultProps) Image.defaultProps.disableFastImage = …
```

feat(CLNP-2540): add disableFastImage prop to Image component

---

packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelInput.tsx
packages/uikit-react-native/src/domain/groupChannel/types.ts
packages/uikit-react-native/src/domain/openChannel/component/OpenChannelInput.tsx
packages/uikit-react-native/src/domain/openChannel/types.ts
packages/uikit-testing-tools/src/mocks/createMockChannel.ts
packages/uikit-testing-tools/src/mocks/createMockMessage.ts
packages/uikit-utils/src/types.ts

[CLNP-2719]
[CLNP-2719]: https://sendbird.atlassian.net/browse/CLNP-2719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CLNP-2719): inputDisabled prop opened as public

---

packages/uikit-react-native-foundation/src/components/Image/Image.fastimage.tsx
packages/uikit-react-native-foundation/src/components/Image/index.ts

[TICKET_ID]
Removed defaultProps assignment

chore: remove default props from image component

---

packages/uikit-react-native/package.json
packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
yarn.lock

uikit-tools 배포후 버전 변경하여 한번더 커밋할 예정입니다.
[CLNP-3585](https://sendbird.atlassian.net/browse/CLNP-3585)
Deprecated enableReactionsSupergroup in SendbirdUIKitContainer
[CLNP-3585]: https://sendbird.atlassian.net/browse/CLNP-3585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CLNP-3585): deprecated enableReactionsSupergroup

---

packages/uikit-react-native/src/hooks/usePushTokenRegistration.ts

[CLNP-5361]
If the API call is not awaited, the token deregistration API call may fail at the time of disconnection
[CLNP-5361]: https://sendbird.atlassian.net/browse/CLNP-5361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-5361] fix: await token apis

---

packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
packages/uikit-react-native/src/components/ChannelThreadMessageList/index.tsx
packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
packages/uikit-react-native/src/contexts/SBUHandlersCtx.tsx
packages/uikit-react-native/src/domain/groupChannelThread/component/GroupChannelThreadParentMessageInfo.tsx

[TICKET_ID]
Since `onOpenFileURL` is called redundantly with `onPressMediaMessage`, to maintain backward compatibility, the default `onOpenFileURL` should perform no action.

fix: remove default onOpenFileURL handler

---

packages/uikit-chat-hooks/src/common/useUserList.ts
packages/uikit-react-native/src/components/ChannelInput/index.tsx
packages/uikit-react-native/src/components/ReactionAddons/BottomSheetReactionAddon.tsx
packages/uikit-react-native/src/components/ReactionBottomSheets/ReactionListBottomSheet.tsx
packages/uikit-react-native/src/hooks/usePushTokenRegistration.ts

[TICKET_ID]
- Fixing the bug that prevents adding and removing reactions.

fix: resolve this binding issues

---

packages/uikit-react-native/src/components/FileViewer/FileViewerContent.tsx
packages/uikit-react-native/src/components/FileViewer/FileViewerFooter.tsx
packages/uikit-react-native/src/components/FileViewer/FileViewerHeader.tsx

[CLNP-5553]
Due to the z-index, this problem occurs only in the New architecture.
[CLNP-5553]: https://sendbird.atlassian.net/browse/CLNP-5553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-5553] fix: ensure image visibility in file viewer on new architecture

---

packages/uikit-react-native/README.md
packages/uikit-react-native/src/platform/createFileService.native.ts
packages/uikit-react-native/src/platform/createPlayerService.native.tsx
sample/android/app/src/main/AndroidManifest.xml

[CLNP-5556]
[CLNP-5556]: https://sendbird.atlassian.net/browse/CLNP-5556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-5556] fix: remove non-required permissions from android

---

packages/uikit-react-native/README.md
packages/uikit-react-native/src/platform/createFileService.native.ts
sample/android/app/src/main/AndroidManifest.xml

[TICKET_ID]
In the image picker library, camera permission is not a mandatory requirement. However, if camera permission is declared in the AndroidManifest.xml, it becomes mandatory to have this permission to call the launchCamera method.
In UIKit, it’s not possible to know if permissions are declared in the customer's app's AndroidManifest.xml, so it enforces the addition and requests the necessary permissions.
What …

fix: revert android camera permission

---

sample/src/libs/notification.ts

Customer inquiry: https://sendbird.slack.com/archives/G016RFZKQ15/p1730856329012129

chore: add notes for notifee

---

packages/uikit-react-native-foundation/src/components/Text/index.tsx
packages/uikit-react-native-foundation/src/components/TextInput/index.tsx
packages/uikit-react-native/src/components/GroupChannelMessageRenderer/index.tsx
packages/uikit-react-native/src/components/ThreadParentMessageRenderer/ThreadParentMessage.file.voice.tsx
packages/uikit-react-native/src/components/ThreadParentMessageRenderer/index.tsx
packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
packages/uikit-react-native/src/libs/MentionConfig.ts
packages/uikit-react-native/src/libs/MentionManager.tsx
packages/uikit-utils/src/index.ts
packages/uikit-utils/src/shared/rtl.ts
sample/src/screens/uikit/openChannel/OpenChannelTabs/OpenChannelListLiveStreamsScreen.tsx

- [CLNP-5611]
- [CLNP-5610]
- [CLNP-5632]
- [CLNP-5655]
- [CLNP-5696]
[CLNP-5611]: https://sendbird.atlassian.net/browse/CLNP-5611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLNP-5610]: …

fix: RTL QA

---

CHANGELOG.md
CHANGELOG_DRAFT.md
docs-validation/CHANGELOG.md
docs-validation/package.json
lerna.json
packages/uikit-chat-hooks/CHANGELOG.md
packages/uikit-chat-hooks/package.json
packages/uikit-react-native-foundation/CHANGELOG.md
packages/uikit-react-native-foundation/package.json
packages/uikit-react-native/CHANGELOG.md
packages/uikit-react-native/package.json
packages/uikit-testing-tools/CHANGELOG.md
packages/uikit-testing-tools/package.json
packages/uikit-utils/CHANGELOG.md
packages/uikit-utils/package.json
sample/CHANGELOG.md
sample/package.json

[SDKRLSD-1478]
[SDKRLSD-1478]: https://sendbird.atlassian.net/browse/SDKRLSD-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDKRLSD-1478] chore: release 3.8.0

---

packages/uikit-react-native/src/components/ChannelInput/index.tsx
packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelSuggestedMentionList.tsx
packages/uikit-react-native/src/domain/groupChannelThread/component/GroupChannelThreadSuggestedMentionList.tsx

[CLNP-5902]
[CLNP-5902]: https://sendbird.atlassian.net/browse/CLNP-5902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-5902] feat: added showUserId config to suggested mention list

---

CHANGELOG.md
CHANGELOG_DRAFT.md
docs-validation/CHANGELOG.md
docs-validation/package.json
lerna.json
packages/uikit-chat-hooks/CHANGELOG.md
packages/uikit-chat-hooks/package.json
packages/uikit-react-native-foundation/CHANGELOG.md
packages/uikit-react-native-foundation/package.json
packages/uikit-react-native/CHANGELOG.md
packages/uikit-react-native/package.json
packages/uikit-testing-tools/CHANGELOG.md
packages/uikit-testing-tools/package.json
packages/uikit-utils/CHANGELOG.md
packages/uikit-utils/package.json
sample/CHANGELOG.md
sample/package.json

[SDKRLSD-1481]
[SDKRLSD-1481]: https://sendbird.atlassian.net/browse/SDKRLSD-1481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDKRLSD-1481] chore: release 3.8.1

---

packages/uikit-react-native-foundation/src/styles/createStyleSheet.ts

[[CLNP-6724]](https://sendbird.atlassian.net/browse/CLNP-6724)
The borderRadius type in StyleSheet [was updated to support string values in React Native 0.75](https://github.com/facebook/react-native/commit/9c4ee6df087f9bc3024d893f1d87d54646661512).
To reflect this change, the parameter and return types were updated from
NonNullable<AnimatableNumericValue | undefined> to
NonNullable<AnimatableNumericValue | string | …

[CLNP-6724] fix: allow string values for borderRadius in StyleSheet

---

packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
packages/uikit-react-native/src/components/ChatFlatList/index.tsx
packages/uikit-react-native/src/domain/groupChannel/types.ts
packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx

[[CLNP-6807]](https://sendbird.atlassian.net/browse/CLNP-6807)
Added flatListComponent to GroupChannelFragment to support customization
[CLNP-6807]: https://sendbird.atlassian.net/browse/CLNP-6807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-6807] feat: add support for custom FlatList component in message list

---

packages/uikit-react-native-foundation/src/components/Modal/index.tsx

[CLNP-6755]
Fixed an issue where BottomSheet components were not appearing when using DrawerNavigator.
This issue occurs only on Android. I have tested it on both iOS and Android.
[CLNP-6755]: https://sendbird.atlassian.net/browse/CLNP-6755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …

[CLNP-6755]fix : BottomSheet not appearing when using DrawerNabigator

---

.github/workflows/publish-package.yml

[CLNP-7153](https://sendbird.atlassian.net/browse/CLNP-7153)
release 브랜치에서 테스트 완료하였습니다
[CLNP-7153]: https://sendbird.atlassian.net/browse/CLNP-7153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: improve version handling in publish-package.yml for security

---

packages/uikit-react-native/src/components/ChannelInput/EditInput.tsx
packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
packages/uikit-react-native/src/components/ChannelInput/index.tsx
packages/uikit-react-native/src/domain/groupChannel/types.ts
packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx

[[CLNP-7474]](https://sendbird.atlassian.net/browse/CLNP-7474)
GroupChannelInput 에서 autoCorrect기능을 on/off 할수 있도록 추가하였습니다.
autoCorrect 가 true 일때 iOS 에서 메세지 전송이후, 텍스트가 남아있는 현상 수정하였습니다.
[CLNP-7474]: https://sendbird.atlassian.net/browse/CLNP-7474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

[CLNP-7474] feat: supprot-for-text-input-props

---

packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelMessageList.tsx
packages/uikit-react-native/src/domain/groupChannel/module/moduleContext.tsx
packages/uikit-react-native/src/domain/groupChannel/types.ts

[[CLNP-7468]](https://sendbird.atlassian.net/browse/CLNP-7468)
search item 을 이용하여 groupChannel 진입시 lazyScrollToIndex를 이용하여 스크롤 처리를 하는데 다음과 같은 문제가 있습니다
1. lazyScrollToIndex 내부에서 timeout 딜레이를 주고 scrollToIndex 를 호출기전에 messages가 변경되면 index가 맞지 않은 문제
2. FlatList에서 내부 조건에 의해 onBottomReached를 호출하는데 collection의 cacheResult 와 apiResult 사이에 onBottomReached 로 인해 loadNext가 호출되면서 FlatList 내부 Data가 변경되며 scroll이 정상정으로 되지 않는 문제
해결방법 …

[CLNP-7468] fix: resolve search item scroll issue

---

packages/uikit-react-native/src/components/ChannelInput/index.tsx

[[CLNP-7507]](https://sendbird.atlassian.net/browse/CLNP-7507)
Android API 35 에서 버튼 네비게이션 사용시 Input 영역히 겹치는 문제 수정하였습니다.
최근에 Android API 35 대응으로 수정된 코드기준으로 키보드가 보이지 않을때는 SafeArea가 적용되어야 합니다.
[CLNP-7507]: https://sendbird.atlassian.net/browse/CLNP-7507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …

[CLNP-7507] fix: improve keyboard handling when using button navigation on API 35

---

CHANGELOG.md
CHANGELOG_DRAFT.md
docs-validation/CHANGELOG.md
docs-validation/package.json
lerna.json
packages/uikit-chat-hooks/CHANGELOG.md
packages/uikit-chat-hooks/package.json
packages/uikit-react-native-foundation/CHANGELOG.md
packages/uikit-react-native-foundation/package.json
packages/uikit-react-native/CHANGELOG.md
packages/uikit-react-native/package.json
packages/uikit-testing-tools/CHANGELOG.md
packages/uikit-testing-tools/package.json
packages/uikit-utils/CHANGELOG.md
packages/uikit-utils/package.json
sample/CHANGELOG.md
sample/package.json

[[SDKRLSD-1756]](https://sendbird.atlassian.net/browse/SDKRLSD-1756)
- add textInputProps to support custom TextInput behavior in GroupChannel
- improve keyboard handling when using button navigation on API 35
- improve handling of autocorrect when sending input on iOS
- resolve issue where search item did not scroll properly
Put an `x` in the boxes that …

[SDKRLSD-1756] release v3.10.2
