- packages/uikit-react-native/src/platform/createFileService.expo.ts
[UIKIT-1995]
[UIKIT-1995]: https://sendbird.atlassian.net/browse/UIKIT-1995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-1995] Fixed createFileService.expo to work as expected

- packages/uikit-chat-hooks/src/channel/useGroupChannelListWithCollection.ts
- packages/uikit-chat-hooks/src/channel/useGroupChannelListWithQuery.ts
- packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/useGroupChannelMessagesWithCollection.ts
- packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/useGroupChannelMessagesWithQuery.ts
- packages/uikit-chat-hooks/src/common/useAppFeatures.ts
- packages/uikit-chat-hooks/src/handler/useChannelHandler.ts
- packages/uikit-react-native-foundation/src/styles/createScaleFactor.ts
- packages/uikit-react-native-foundation/src/ui/GroupChannelPreview/index.tsx
- packages/uikit-react-native/src/SendbirdUIKitContainer.tsx
- packages/uikit-react-native/src/components/GroupChannelPreviewContainer.tsx
- packages/uikit-react-native/src/components/MessageRenderer/MessageOutgoingStatus.tsx
- packages/uikit-react-native/src/components/SBUPressable.tsx
- packages/uikit-react-native/src/components/UserActionBar.tsx
- packages/uikit-react-native/src/components/UserSelectableBar.tsx
- packages/uikit-react-native/src/contexts/SendbirdChat.tsx
- packages/uikit-react-native/src/domain/groupChannel/module/moduleContext.tsx
- packages/uikit-react-native/src/domain/groupChannelList/types.ts
- packages/uikit-react-native/src/domain/groupChannelSettings/module/moduleContext.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelCreateFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelListFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelMembersFragment.tsx
- packages/uikit-react-native/src/hooks/useContext.ts
- sample/ios/Podfile.lock
- sample/src/App.tsx
[UIKIT-2111] typing indicator
[UIKIT-2112] receipt status
[UIKIT-2111]: https://sendbird.atlassian.net/browse/UIKIT-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UIKIT-2112]: …
> Feat/Typing indicator, Receipt status in GroupChannelList

- packages/uikit-chat-hooks/src/channel/useGroupChannelList/useGroupChannelListWithCollection.ts
- packages/uikit-react-native/src/components/FileViewer.tsx
- packages/uikit-react-native/src/components/MessageRenderer/FileMessage/ImageFileMessage.tsx
- packages/uikit-react-native/src/components/MessageRenderer/MessageIncomingSenderName.tsx
- packages/uikit-react-native/src/components/MessageRenderer/index.tsx
- packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelInput/SendInput.tsx
- packages/uikit-react-native/src/domain/groupChannelSettings/module/moduleContext.tsx
- packages/uikit-react-native/src/libs/SBUError.ts
- packages/uikit-react-native/src/libs/SBUUtils.ts
- packages/uikit-react-native/src/localization/StringSet.type.ts
- packages/uikit-react-native/src/platform/createFileService.expo.ts
- packages/uikit-react-native/src/platform/createFileService.native.ts
- packages/uikit-react-native/src/platform/types.ts
- packages/uikit-utils/package.json
- packages/uikit-utils/src/shared/regex.ts
- sample/src/screens/uikit-app/GroupChannelTabs/SettingsScreen.tsx
[QM-1763]
[QM-1763]: https://sendbird.atlassian.net/browse/QM-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QM-1763]Fix/video file message, file viewer

- packages/uikit-chat-hooks/src/common/useMessageOutgoingStatus.ts
- packages/uikit-react-native-foundation/src/ui/GroupChannelPreview/index.tsx
- packages/uikit-react-native/src/containers/GroupChannelPreviewContainer.tsx
- packages/uikit-react-native/src/domain/groupChannelList/types.ts
- packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelListFragment.tsx
- packages/uikit-utils/src/sendbird/channel.ts
- packages/uikit-utils/src/shared/bufferedRequest.ts
[UIKIT-2166]
[UIKIT-2166]: https://sendbird.atlassian.net/browse/UIKIT-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-2166] Feat/group channel types

- packages/uikit-react-native-foundation/src/ui/Toast/index.tsx
- packages/uikit-react-native/src/contexts/SendbirdChat.tsx
- sample/index.js
- sample/ios/Podfile.lock
- sample/package.json
- sample/src/App.tsx
- sample/src/libs/logView.tsx
[UIKIT-2363]
[UIKIT-2363]: https://sendbird.atlassian.net/browse/UIKIT-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-2363] v1/fix/auto resend ios

- packages/uikit-react-native-foundation/src/ui/Toast/index.tsx
- packages/uikit-react-native/src/contexts/SendbirdChat.tsx
- sample/index.js
- sample/src/App.tsx
- sample/src/libs/logView.tsx
[UIKIT-2363]
[UIKIT-2363]: https://sendbird.atlassian.net/browse/UIKIT-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-2363] v2/hotfix/auto resend ios 

- packages/uikit-react-native/src/localization/StringSet.type.ts
- packages/uikit-utils/src/sendbird/message.ts
- packages/uikit-utils/src/ui-format/common.ts
- packages/uikit-utils/src/ui-format/groupChannel.ts
[UIKIT-2580]
[UIKIT-2580]: https://sendbird.atlassian.net/browse/UIKIT-2580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-2580] enhancement: update time format

- packages/uikit-react-native/src/contexts/SendbirdChatCtx.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelListFragment.tsx
- packages/uikit-utils/package.json
- packages/uikit-utils/src/hooks/index.ts
- packages/uikit-utils/src/hooks/react-native.ts
- packages/uikit-utils/src/index.ts
> Fix/v2/support compatibility for removing AppState listener under 0.65

- packages/uikit-react-native/src/contexts/SendbirdChat.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelListFragment.tsx
- packages/uikit-utils/package.json
- packages/uikit-utils/src/hooks/react-native.ts
- packages/uikit-utils/src/index.ts
> Fix/v1/support compatibility for removing AppState listener under 0.65

- packages/uikit-react-native/src/contexts/PlatformServiceCtx.tsx
- packages/uikit-react-native/src/contexts/SendbirdChatCtx.tsx
[UIKIT-2995]
[UIKIT-2995]: https://sendbird.atlassian.net/browse/UIKIT-2995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-2995] Fix/fixed to useContext type compiles the correct package path

- CHANGELOG.md
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
[SDKRLSD-655]
[SDKRLSD-655]: https://sendbird.atlassian.net/browse/SDKRLSD-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-655] Release/1.1.4

- catalog-info.yaml
[UIKIT-3113]
[UIKIT-3113]: https://sendbird.atlassian.net/browse/UIKIT-3113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3113] Chore/added catalog-info.yaml

- CHANGELOG.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-669]
[SDKRLSD-669]: https://sendbird.atlassian.net/browse/SDKRLSD-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-669] Release/2.3.0

- packages/uikit-react-native/src/domain/openChannelModeration/component/OpenChannelModerationHeader.tsx
- packages/uikit-react-native/src/domain/openChannelModeration/component/OpenChannelModerationMenu.tsx
- packages/uikit-react-native/src/domain/openChannelModeration/index.ts
- packages/uikit-react-native/src/domain/openChannelModeration/module/createOpenChannelModerationModule.tsx
- packages/uikit-react-native/src/domain/openChannelModeration/module/moduleContext.tsx
- packages/uikit-react-native/src/domain/openChannelModeration/types.ts
- packages/uikit-react-native/src/fragments/createOpenChannelModerationFragment.tsx
- packages/uikit-react-native/src/index.ts
- packages/uikit-react-native/src/localization/StringSet.type.ts
- packages/uikit-react-native/src/localization/createBaseStringSet.ts
- sample/src/App.tsx
- sample/src/libs/navigation.ts
- sample/src/screens/uikit/openChannel/OpenChannelModerationScreen.tsx
- sample/src/screens/uikit/openChannel/OpenChannelSettingsScreen.tsx
- sample/src/screens/uikit/openChannel/index.ts
[UIKIT-2845]
[UIKIT-2845]: https://sendbird.atlassian.net/browse/UIKIT-2845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-2845] Feat/open channel moderation

- package.json
- packages/uikit-react-native/src/domain/groupChannelBannedUsers/index.ts
- packages/uikit-react-native/src/domain/openChannelBannedUsers/component/OpenChannelBannedUsersHeader.tsx
- packages/uikit-react-native/src/domain/openChannelBannedUsers/component/OpenChannelBannedUsersList.tsx
- packages/uikit-react-native/src/domain/openChannelBannedUsers/component/OpenChannelBannedUsersStatusEmpty.tsx
- packages/uikit-react-native/src/domain/openChannelBannedUsers/component/OpenChannelBannedUsersStatusError.tsx
- packages/uikit-react-native/src/domain/openChannelBannedUsers/component/OpenChannelBannedUsersStatusLoading.tsx
- packages/uikit-react-native/src/domain/openChannelBannedUsers/index.ts
- packages/uikit-react-native/src/domain/openChannelBannedUsers/module/createOpenChannelBannedUsersModule.tsx
- packages/uikit-react-native/src/domain/openChannelBannedUsers/module/moduleContext.tsx
- packages/uikit-react-native/src/domain/openChannelBannedUsers/types.ts
- packages/uikit-react-native/src/fragments/createOpenChannelBannedUsersFragment.tsx
- packages/uikit-react-native/src/index.ts
- packages/uikit-react-native/src/localization/StringSet.type.ts
- packages/uikit-react-native/src/localization/createBaseStringSet.ts
- sample/src/App.tsx
- sample/src/libs/navigation.ts
- sample/src/screens/uikit/openChannel/OpenChannelBannedUsersScreen.tsx
- sample/src/screens/uikit/openChannel/OpenChannelModerationScreen.tsx
- sample/src/screens/uikit/openChannel/index.ts
[UIKIT-3173]
[UIKIT-3173]: https://sendbird.atlassian.net/browse/UIKIT-3173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3173] Feat/added open channel banned users fragment

- packages/uikit-react-native/__template__/component/__domain__StatusEmpty.tsx
- packages/uikit-react-native/__template__/component/__domain__StatusLoading.tsx
- packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
- packages/uikit-react-native/src/domain/openChannelOperators/component/OpenChannelOperatorsHeader.tsx
- packages/uikit-react-native/src/domain/openChannelOperators/component/OpenChannelOperatorsList.tsx
- packages/uikit-react-native/src/domain/openChannelOperators/component/OpenChannelOperatorsStatusEmpty.tsx
- packages/uikit-react-native/src/domain/openChannelOperators/component/OpenChannelOperatorsStatusError.tsx
- packages/uikit-react-native/src/domain/openChannelOperators/component/OpenChannelOperatorsStatusLoading.tsx
- packages/uikit-react-native/src/domain/openChannelOperators/index.ts
- packages/uikit-react-native/src/domain/openChannelOperators/module/createOpenChannelOperatorsModule.tsx
- packages/uikit-react-native/src/domain/openChannelOperators/module/moduleContext.tsx
- packages/uikit-react-native/src/domain/openChannelOperators/types.ts
- packages/uikit-react-native/src/domain/openChannelUserList/types.ts
- packages/uikit-react-native/src/fragments/createOpenChannelOperatorsFragment.tsx
- packages/uikit-react-native/src/fragments/createOpenChannelRegisterOperatorFragment.tsx
- packages/uikit-react-native/src/index.ts
- packages/uikit-react-native/src/localization/StringSet.type.ts
- packages/uikit-react-native/src/localization/createBaseStringSet.ts
- sample/src/screens/uikit/openChannel/OpenChannelOperatorsScreen.tsx
- sample/src/screens/uikit/openChannel/OpenChannelRegisterOperatorScreen.tsx
[UIKIT-3174]
[UIKIT-3175]
[UIKIT-3174]: https://sendbird.atlassian.net/browse/UIKIT-3174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UIKIT-3175]: …
> [UIKIT-3174] Feat/open channel operators

- packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
[UIKIT-3393]
[UIKIT-3393]: https://sendbird.atlassian.net/browse/UIKIT-3393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3393] Enhancement/disabled option for error boundary

- packages/uikit-utils/src/shared/regex.ts
[UIKIT-3427]
[UIKIT-3427]: https://sendbird.atlassian.net/browse/UIKIT-3427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3427] Fix/v1/fixed file download on android 

- CHANGELOG.md
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
[SDKRLSD-737]
[SDKRLSD-737]: https://sendbird.atlassian.net/browse/SDKRLSD-737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-737] Release/1.1.5

- docs-validation/1_introduction/SendYourFirstMessage.tsx
- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
- packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
- packages/uikit-react-native/src/contexts/SendbirdChatCtx.tsx
- packages/uikit-react-native/src/hooks/libs/useEmojiManager.ts
- packages/uikit-react-native/src/hooks/libs/useImageCompressionConfig.ts
- packages/uikit-react-native/src/hooks/libs/useInternalStorage.ts
- packages/uikit-react-native/src/hooks/libs/useMentionManager.ts
- packages/uikit-react-native/src/index.ts
- packages/uikit-react-native/src/libs/GiphyService.ts
- packages/uikit-react-native/src/localization/StringSet.type.ts
- packages/uikit-react-native/src/localization/createBaseStringSet.ts
- sample/ios/Podfile.lock
- sample/package.json
- sample/src/App.tsx
- yarn.lock
[UIKIT-3507]
[UIKIT-3507]: https://sendbird.atlassian.net/browse/UIKIT-3507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3507] POC/Giphy

- packages/uikit-chat-hooks/README.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/README.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/README.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/README.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/README.md
- packages/uikit-utils/package.json
[UIKIT-3584]
[UIKIT-3584]: https://sendbird.atlassian.net/browse/UIKIT-3584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3584] Chore/SEO

- packages/uikit-react-native/src/domain/groupChannelBannedUsers/types.ts
- packages/uikit-react-native/src/domain/groupChannelMutedMembers/types.ts
- packages/uikit-react-native/src/domain/groupChannelOperators/types.ts
- packages/uikit-react-native/src/domain/groupChannelUserList/types.ts
- packages/uikit-react-native/src/domain/openChannelBannedUsers/types.ts
- packages/uikit-react-native/src/domain/openChannelMutedParticipants/types.ts
- packages/uikit-react-native/src/domain/openChannelOperators/types.ts
- packages/uikit-react-native/src/domain/openChannelUserList/types.ts
- packages/uikit-react-native/src/fragments/createGroupChannelBannedUsersFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelMembersFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelMutedMembersFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelNotificationsFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelOperatorsFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelRegisterOperatorFragment.tsx
- packages/uikit-react-native/src/fragments/createOpenChannelBannedUsersFragment.tsx
- packages/uikit-react-native/src/fragments/createOpenChannelMutedParticipantsFragment.tsx
- packages/uikit-react-native/src/fragments/createOpenChannelOperatorsFragment.tsx
- packages/uikit-react-native/src/fragments/createOpenChannelParticipantsFragment.tsx
- packages/uikit-react-native/src/fragments/createOpenChannelRegisterOperatorFragment.tsx
[UIKIT-3756]
[UIKIT-3756]: https://sendbird.atlassian.net/browse/UIKIT-3756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3756] Feat/query creators

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/ios/Podfile.lock
- sample/package.json
- sample/src/components/HomeListItem.tsx
- sample/src/screens/HomeScreen.tsx
[SDKRLSD-797](https://sendbird.atlassian.net/browse/SDKRLSD-797)
[SDKRLSD-797]: https://sendbird.atlassian.net/browse/SDKRLSD-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-797] Release/2.4.2

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- package.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/README.md
- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/components/ChatFlatList.tsx
- packages/uikit-react-native/src/domain/messageSearch/component/MessageSearchList.tsx
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-testing-tools/src/mocks/createMockChannel.ts
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-804](https://sendbird.atlassian.net/browse/SDKRLSD-804)
[SDKRLSD-804]: https://sendbird.atlassian.net/browse/SDKRLSD-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-804] Release/2.5.0

- packages/uikit-react-native/src/domain/groupChannelSettings/component/GroupChannelSettingsMenu.tsx
[UIKIT-3864]
[UIKIT-3864]: https://sendbird.atlassian.net/browse/UIKIT-3864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3864] Fix/fixed menuItemsCreator timing

- packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
- packages/uikit-react-native/src/components/MessageRenderer/MessageOutgoingStatus.tsx
- packages/uikit-react-native/src/containers/GroupChannelPreviewContainer.tsx
- packages/uikit-react-native/src/domain/groupChannelSettings/component/GroupChannelSettingsMenu.tsx
- packages/uikit-utils/src/sendbird/message.ts
[UIKIT-3378]
[UIKIT-3378]: https://sendbird.atlassian.net/browse/UIKIT-3378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3378] Feat/hide ui elements when the channel is ephemeral

- packages/uikit-react-native/src/components/MessageRenderer/UserMessage/index.tsx
- packages/uikit-react-native/src/components/OpenChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
- packages/uikit-react-native/src/contexts/SendbirdChatCtx.tsx
- packages/uikit-react-native/src/contexts/UserProfileCtx.tsx
- sample/src/App.tsx
[UIKIT-3705]
[UIKIT-3705]: https://sendbird.atlassian.net/browse/UIKIT-3705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3705] Feat/uikit options

- packages/uikit-react-native/src/fragments/createGroupChannelCreateFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelInviteFragment.tsx
[UIKIT-3888]
[UIKIT-3888]: https://sendbird.atlassian.net/browse/UIKIT-3888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3888] Fix/replaced unsupported Object.hasOwn

- packages/uikit-react-native-foundation/src/components/ImageWithPlaceholder/index.tsx
- packages/uikit-react-native-foundation/src/components/RegexText/index.tsx
- packages/uikit-react-native-foundation/src/index.ts
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.admin.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.file.image.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.file.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.file.video.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.unknown.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.user.og.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.user.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/MessageBubble.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/MessageBubbleWithText.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/MessageContainer.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/MessageOpenGraph.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/index.ts
- packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageDateSeparator.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageFocusAnimation.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageOutgoingStatus.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/components/MessageRenderer/UserMessage/BaseUserMessage.tsx
- packages/uikit-react-native/src/components/MessageRenderer/index.tsx
- packages/uikit-react-native/src/components/OpenChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
- packages/uikit-react-native/src/fragments/createOpenChannelFragment.tsx
- packages/uikit-react-native/src/libs/MentionManager.tsx
[UIKIT-3886]
[UIKIT-3886]: https://sendbird.atlassian.net/browse/UIKIT-3886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-3886] Refactor/group channel message

- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/components/ChannelInput/AttachmentsButton.tsx
- packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
- packages/uikit-react-native/src/components/ChannelInput/index.tsx
- packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelInput.tsx
- packages/uikit-react-native/src/domain/groupChannel/types.ts
- packages/uikit-react-native/src/domain/openChannel/component/OpenChannelInput.tsx
- packages/uikit-react-native/src/domain/openChannel/types.ts
- yarn.lock
[UIKIT-4129]
Added attachments button prop to channel input to customize attachments button easily.
[UIKIT-4129]: https://sendbird.atlassian.net/browse/UIKIT-4129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(UIKIT-4129): channel input components

- packages/uikit-react-native/src/components/ChatFlatList/FlatListInternal.tsx
- sample/src/App.tsx
> fix: flatlist internal condition

- packages/uikit-react-native/src/components/ChatFlatList/FlatListInternal.tsx
[UIKIT-4241]
revert ff48e36
For `< 0.72`, onStartReached is only available using the scroll view enhancer
[UIKIT-4241]: https://sendbird.atlassian.net/browse/UIKIT-4241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(UIKIT-4241): revert "ff48e36"

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-900]
[SDKRLSD-900]: https://sendbird.atlassian.net/browse/SDKRLSD-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(SDKRLSD-900): hotfix 3.0.2

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/utils/normalizeFile.ts
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-904]
[SDKRLSD-904]: https://sendbird.atlassian.net/browse/SDKRLSD-904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(SDKRLSD-904): hotfix 3.0.3

- jest.setup.js
- package.json
- packages/uikit-react-native/src/__tests__/utils/normalizeFile.test.ts
- packages/uikit-utils/src/__tests__/shared/file.test.ts
- packages/uikit-utils/src/shared/file.ts
- yarn.lock
[CLNP-386]
I have fixed the bugs in the utilities that handle file names, types, extensions, and other aspects in React Native.
The fixes also ensure that files are properly sent in the Expo environment.
[CLNP-386]: https://sendbird.atlassian.net/browse/CLNP-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> fix(CLNP-386): file utils

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/platform/createFileService.expo.ts
- packages/uikit-react-native/src/platform/createFileService.native.ts
- packages/uikit-react-native/src/utils/expoBackwardUtils.ts
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
- yarn.lock
[SDKRLSD-906]
[SDKRLSD-906]: https://sendbird.atlassian.net/browse/SDKRLSD-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(SDKRLSD-906): hotfix 3.0.4

- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/MessageContainer.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/index.ts
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageParentMessage.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelMessageList.tsx
- packages/uikit-react-native/src/localization/StringSet.type.ts
- packages/uikit-react-native/src/localization/createBaseStringSet.ts
- packages/uikit-utils/src/sendbird/message.ts
[UIKIT-4248]
- separate `ParentMessage` component into a separate file
- apply parent message composition to the `GroupChannelMessage` component
- update some design details
- add exception handling for unreachable parent message
[UIKIT-4248]: https://sendbird.atlassian.net/browse/UIKIT-4248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(UIKIT-4248): update design details

- packages/uikit-react-native-foundation/src/ui/BottomSheet/index.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/MessageContainer.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/index.ts
- packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
- packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageParentMessage.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelMessageList.tsx
- packages/uikit-react-native/src/localization/StringSet.type.ts
- packages/uikit-react-native/src/localization/createBaseStringSet.ts
- packages/uikit-utils/src/sendbird/message.ts
- tsconfig.json
[UIKIT-4247]
[UIKIT-4247]: https://sendbird.atlassian.net/browse/UIKIT-4247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UIKIT-4247] Feat/quote reply design

- packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/useGroupChannelMessagesWithCollection.ts
- packages/uikit-chat-hooks/src/types.ts
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/MessageContainer.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageParentMessage.tsx
- packages/uikit-react-native/src/domain/groupChannel/types.ts
- packages/uikit-react-native/src/domain/openChannel/types.ts
- packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
- packages/uikit-react-native/src/utils/pubsub.ts
[UIKIT-4249]
[UIKIT-4249]: https://sendbird.atlassian.net/browse/UIKIT-4249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(UIKIT-4249): parent message update

- sample/ios/SendbirdUIKitSample.xcodeproj/project.pbxproj
- sample/ios/fastlane/Matchfile
[TICKET_ID]
(Internal) Changes for iOS sample release automation
> chore: update match git branch

- packages/uikit-react-native/src/platform/types.ts
[CLNP-552]
Customer request from [community](https://community.sendbird.com/t/missing-type-exports/)
[CLNP-552]: https://sendbird.atlassian.net/browse/CLNP-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(CLNP-552): export media service related types

- package.json
- packages/uikit-react-native-foundation/src/components/VideoThumbnail/index.tsx
- packages/uikit-react-native/src/components/ChannelInput/index.tsx
- packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
- packages/uikit-react-native/src/localization/createBaseStringSet.ts
- packages/uikit-react-native/src/platform/createMediaService.native.tsx
- packages/uikit-testing-tools/src/mocks/createMockChannel.ts
- packages/uikit-testing-tools/src/mocks/createMockGroupChannelCollection.ts
- packages/uikit-utils/src/types.ts
- yarn.lock
[UIKIT-4261]
[UIKIT-4308]
[UIKIT-4261]: https://sendbird.atlassian.net/browse/UIKIT-4261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UIKIT-4308]: …
> chore(UIKIT-4261): quote reply qa fix 3

- docs-validation/package.json
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
- packages/uikit-react-native/src/contexts/SendbirdChatCtx.tsx
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/package.json
- sample/package.json
- yarn.lock
[CLNP-204]
[CLNP-204]: https://sendbird.atlassian.net/browse/CLNP-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(CLNP-204): user-agent revamp

- docs-validation/2_features/QuoteReply.tsx
- docs-validation/4_key-functions/ChattingInAChannel/ChatInAGroupChannel.tsx
[UIKIT-4319]
[UIKIT-4319]: https://sendbird.atlassian.net/browse/UIKIT-4319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(UIKIT-4319): add quote-reply docs-validation

- sample/DEPLOYMENT.md
[CLNP-486]
[CLNP-486]: https://sendbird.atlassian.net/browse/CLNP-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(CLNP-486): add sample deployment.md

- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.file.image.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.file.video.tsx
- packages/uikit-react-native-foundation/src/ui/OpenChannelMessage/Message.file.image.tsx
- packages/uikit-react-native-foundation/src/ui/OpenChannelMessage/Message.file.video.tsx
- packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageParentMessage.tsx
- packages/uikit-utils/src/sendbird/message.ts
[CLNP-733]
[CLNP-733]: https://sendbird.atlassian.net/browse/CLNP-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(CLNP-733): use thumbnails if available

- packages/uikit-react-native-foundation/src/components/VideoThumbnail/index.tsx
- packages/uikit-react-native-foundation/src/ui/GroupChannelMessage/Message.file.video.tsx
- packages/uikit-react-native-foundation/src/ui/OpenChannelMessage/Message.file.video.tsx
- packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageParentMessage.tsx
> fix: use source as a thumbnail if it is an image

- packages/uikit-react-native-foundation/src/theme/DarkUIKitTheme.ts
- packages/uikit-react-native-foundation/src/theme/LightUIKitTheme.ts
- packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
- packages/uikit-react-native/src/hooks/useVoiceMessageInput.ts
- packages/uikit-react-native/src/localization/StringSet.type.ts
- packages/uikit-react-native/src/localization/createBaseStringSet.ts
[UIKIT-4342]
Add string set and exception handling for voice message
[UIKIT-4342]: https://sendbird.atlassian.net/browse/UIKIT-4342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(UIKIT-4342): voice message exception handling

- package.json
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
- packages/uikit-react-native/src/hooks/useVoiceMessageInput.ts
- packages/uikit-react-native/src/index.ts
- packages/uikit-react-native/src/libs/SBUUtils.ts
- packages/uikit-react-native/src/platform/createPlayerService.expo.tsx
- packages/uikit-react-native/src/platform/createRecorderService.expo.tsx
- packages/uikit-react-native/src/platform/createRecorderService.native.tsx
- packages/uikit-react-native/src/platform/types.ts
- packages/uikit-utils/package.json
- yarn.lock
[UIKIT-4337]
- Add Recorder and Player for Expo
- Add `yalc` for local deployment
[UIKIT-4337]: https://sendbird.atlassian.net/browse/UIKIT-4337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(UIKIT-4337): recorder and player for expo

- packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
- packages/uikit-utils/src/types.ts
[CLNP-1046]
Add localCacheEncryption interface
[CLNP-1046]: https://sendbird.atlassian.net/browse/CLNP-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(CLNP-1046): add localCacheEncryption interface to container prop

- sample/android/fastlane/Fastfile
[TICKET_ID]
- Add external group to firebase app distribution groups (for QE team)
> chore(ci/cd): update firebase app distribution groups

- packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelMessageList.tsx
- packages/uikit-react-native/src/domain/groupChannel/module/moduleContext.tsx
- packages/uikit-react-native/src/domain/groupChannel/types.ts
- packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
- packages/uikit-utils/src/hooks/index.ts
[UIKIT-4566]
Export a scrollToMessage function.
```ts
const ComponentInGroupChannelFragment = ({ message }) => {
const { scrollToMessage } = useContext(GroupChannelContexts.Fragment);
function scrollToLastMessage(message) {
const messageIncludedInMessageList = scrollToMessage(message.messageId, { focusAnimated: true, viewPosition: 1 });
if (!messageIncludedInMessageList) {
console.warn('Message not found in the message …
```
> feat(UIKIT-4566): add scrollToMessage to group channel contexts

- packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
[CLNP-1537]
- Add `bottomSheetItem` to the props of `renderMessage` to customize the message menu.
- Refactor `useCreateMessagePressActions`
```tsx
const GroupChannelScreen = () => {
const { openSheet } = useBottomSheet();
return (
<GroupChannelFragment
renderMessage={(props) => {
return (
<GroupChannelMessageRenderer
{...props}
onLongPress={() => {
if (props.bottomSheetItem) {
openSheet({
...props.bottomSheetItem, …
```
> feat(CLNP-1537): add bottomSheetItem to props of renderMessage

- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelMessageList.tsx
- packages/uikit-react-native/src/domain/groupChannel/types.ts
[CLNP-1459]
[CLNP-1459]: https://sendbird.atlassian.net/browse/CLNP-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(CLNP-1459): not scrolled to bottom on android when typing bubble is rendered

- packages/uikit-react-native-foundation/src/ui/Prompt/index.tsx
- packages/uikit-react-native/src/domain/messageSearch/component/MessageSearchHeader.tsx
- packages/uikit-react-native/src/domain/openChannelCreate/component/OpenChannelCreateProfileInput.tsx
[TICKET_ID]
- Replace `padding`, `paddingHorizontal` and `paddingVertical` with `paddingTop`, `paddingRight`, `paddingBottom` and `paddingLeft` in the input style (due to bug in react-native).
> fix: replace padding with specific directions

- packages/uikit-react-native/package.json
- yarn.lock
> chore: update uikit-tools

- docs-validation/4_key-functions/ChattingInAChannel/ChatInAGroupChannel.tsx
- docs-validation/4_key-functions/ListChannels.tsx
- packages/uikit-testing-tools/src/mocks/createMockChannel.ts
[CLNP-2197]
https://github.com/sendbird/SendBird-Docs/pull/4821
[CLNP-2197]: https://sendbird.atlassian.net/browse/CLNP-2197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(CLNP-2197): update docs-validation for new props

- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageOutgoingStatus.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelListFragment.tsx
- packages/uikit-utils/src/types.ts
> fix: remove conditional hooks even if they depend on an unchanging value

- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/contexts/ReactionCtx.tsx
- packages/uikit-react-native/src/contexts/SendbirdChatCtx.tsx
- packages/uikit-utils/src/sendbird/message.ts
- yarn.lock
[CLNP-2026]
---
- spec: https://sendbird.atlassian.net/wiki/spaces/UK/pages/2265614898/Reactions+for+Super+Group+Channel
[CLNP-2026]: https://sendbird.atlassian.net/browse/CLNP-2026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
> feat(CLNP-2026): support reactions for super group channel

- packages/uikit-react-native/src/libs/SBUUtils.ts
[TICKET_ID]
---
Reflect changes of https://github.com/sendbird/sendbird-uikit-react/pull/907
> chore: update openURL logic

- packages/uikit-react-native/README.md
- packages/uikit-react-native/src/platform/createFileService.expo.ts
- packages/uikit-react-native/src/platform/createFileService.native.ts
- sample/ios/Podfile
- sample/ios/Podfile.lock
- sample/ios/SendbirdUIKitSample.xcodeproj/project.pbxproj
- sample/ios/SendbirdUIKitSample/Info.plist
[CLNP-2732]
[CLNP-2732]: https://sendbird.atlassian.net/browse/CLNP-2732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(CLNP-2732): remove unused ios media library permission

- packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelInput.tsx
- packages/uikit-react-native/src/domain/openChannel/component/OpenChannelInput.tsx
[CLNP-2719]
[CLNP-2719]: https://sendbird.atlassian.net/browse/CLNP-2719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(CLNP-2719): when frozen or muted, input should be disabled

- packages/uikit-utils/src/__tests__/shared/file.test.ts
- packages/uikit-utils/src/shared/file.ts
[CLNP-3471]
[CLNP-3471]: https://sendbird.atlassian.net/browse/CLNP-3471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: handle image/jpg mime type to determine image compress properly

- .circleci/config.yml
- .github/workflows/ci.yml
- .github/workflows/comment-bot.yml
- .github/workflows/publish-package.yml
- .github/workflows/publish-sample.yml
- RELEASE_GUIDE.md
[CLNP-3509]
[CLNP-3509]: https://sendbird.atlassian.net/browse/CLNP-3509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci(CLNP-3509): add publish package workflow

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1312](https://sendbird.atlassian.net/browse/SDKRLSD-1312)
[SDKRLSD-1312]: https://sendbird.atlassian.net/browse/SDKRLSD-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: release 3.5.4

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1340](https://sendbird.atlassian.net/browse/SDKRLSD-1340)
[SDKRLSD-1340]: https://sendbird.atlassian.net/browse/SDKRLSD-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: release 3.6.0

- packages/uikit-chat-hooks/src/channel/useGroupChannelList/index.ts
- packages/uikit-chat-hooks/src/channel/useGroupChannelList/useGroupChannelListWithCollection.ts
- packages/uikit-chat-hooks/src/channel/useGroupChannelList/useGroupChannelListWithQuery.ts
- packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/index.ts
- packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/useGroupChannelMessagesWithCollection.ts
- packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/useGroupChannelMessagesWithQuery.ts
- packages/uikit-chat-hooks/src/handler/useChannelHandler.ts
- packages/uikit-chat-hooks/src/types.ts
> chore: add deprecation marks to hooks

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
> chore: release 3.7.0

- docs-validation/4_key-functions/ChattingInAChannel/ChatInAGroupChannel.tsx
- docs-validation/4_key-functions/ChattingInAChannel/ChatInAnOpenChannel.tsx
- docs-validation/4_key-functions/ConfiguringChannelSettings/ConfigureGroupChannelSettings.tsx
- docs-validation/4_key-functions/ConfiguringChannelSettings/ConfigureOpenChannelSettings.tsx
- docs-validation/4_key-functions/CreatingAChannel/CreateAGroupChannel.tsx
- docs-validation/4_key-functions/InviteUsers.tsx
- docs-validation/4_key-functions/ListChannels.tsx
- docs-validation/4_key-functions/ListingUsers/ListBannedUsersInGroupChannel.tsx
- docs-validation/4_key-functions/ListingUsers/ListBannedUsersInOpenChannel.tsx
- docs-validation/4_key-functions/ListingUsers/ListChannelMembers.tsx
- docs-validation/4_key-functions/ListingUsers/ListChannelParticipants.tsx
- docs-validation/4_key-functions/ListingUsers/ListMutedMembers.tsx
- docs-validation/4_key-functions/ListingUsers/ListMutedParticipants.tsx
- docs-validation/4_key-functions/ListingUsers/ListOperatorsInGroupChannel.tsx
- docs-validation/4_key-functions/ListingUsers/ListOperatorsInOpenChannel.tsx
- docs-validation/4_key-functions/ModeratingChannelsAndMembers/ModerateGroupChannelsAndMembers.tsx
- docs-validation/4_key-functions/ModeratingChannelsAndMembers/ModerateOpenChannelsAndParticipants.tsx
- docs-validation/4_key-functions/RegisteringAsOperator/RegisterMemberAsOperators.tsx
- docs-validation/4_key-functions/RegisteringAsOperator/RegisterParticipantsAsOperators.tsx
- docs-validation/4_key-functions/SearchMessage.tsx
[CLNP-4314]
changes from: https://github.com/sendbird/SendBird-Docs/pull/5165
[CLNP-4314]: https://sendbird.atlassian.net/browse/CLNP-4314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(CLNP-4314): update customization code

- sample/package.json
> chore: update scripts

- packages/uikit-react-native/src/contexts/SendbirdChatCtx.tsx
[TICKET_ID]
To avoid unintentionally clearing the cache, the connection is terminated by calling `disconnectWebsocket`. 
> fix: disconnect ws only on unmounted

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1401]
[SDKRLSD-1401]: https://sendbird.atlassian.net/browse/SDKRLSD-1401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: release 3.7.1

- sample/README.md
[SBISSUE-17000]
[SBISSUE-17000]: https://sendbird.atlassian.net/browse/SBISSUE-17000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SBISSUE-17000] docs: add requirements to sample

- packages/uikit-react-native/src/components/ChannelMessageList/index.tsx
- packages/uikit-react-native/src/components/ChannelThreadMessageList/index.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/components/OpenChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/components/ThreadParentMessageRenderer/index.tsx
- packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
- packages/uikit-react-native/src/contexts/SBUHandlersCtx.tsx
- packages/uikit-react-native/src/domain/groupChannelThread/component/GroupChannelThreadParentMessageInfo.tsx
- packages/uikit-react-native/src/hooks/useContext.ts
[CLNP-5024]
```tsx
<SendbirdUIKitContainer
appId={APP_ID}
handlers={{
onOpenURL: (url) => {
console.log('onOpenURL', url);
},
onOpenFileURL: (url) => {
console.log('onOpenFileURL', url);
},
}}
/>
```
[CLNP-5024]: https://sendbird.atlassian.net/browse/CLNP-5024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> [CLNP-5024] feat: added sbu handlers interface

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1420]
[SDKRLSD-1420]: https://sendbird.atlassian.net/browse/SDKRLSD-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: release 3.7.2

- docs-validation/7_resources/StringResource.tsx
- docs-validation/package.json
- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/GroupChannelMessageDateSeparator.tsx
- packages/uikit-react-native/src/components/OpenChannelMessageRenderer/OpenChannelMessageDateSeparator.tsx
- packages/uikit-react-native/src/localization/StringSet.en.ts
- packages/uikit-utils/package.json
- sample/ios/SendbirdUIKitSample.xcodeproj/project.pbxproj
- yarn.lock
[CLNP-5362]
Stable compatibility for date-fns
[CLNP-5362]: https://sendbird.atlassian.net/browse/CLNP-5362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLNP-5362] chore: update date-fns version range and set as peer dependency

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1437]
[SDKRLSD-1437]: https://sendbird.atlassian.net/browse/SDKRLSD-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1437] chore: release 3.7.3

- packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/useGroupChannelMessagesWithCollection.ts
- packages/uikit-chat-hooks/src/channel/useGroupChannelMessages/useGroupChannelMessagesWithQuery.ts
- packages/uikit-react-native/src/components/ChannelInput/VoiceMessageInput.tsx
- packages/uikit-react-native/src/components/ChannelInput/index.tsx
- packages/uikit-react-native/src/components/GroupChannelMessageRenderer/index.tsx
- packages/uikit-react-native/src/components/ReactionAddons/BottomSheetReactionAddon.tsx
- packages/uikit-react-native/src/components/ReactionBottomSheets/ReactionListBottomSheet.tsx
- packages/uikit-react-native/src/components/ThreadParentMessageRenderer/index.tsx
- packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelMessageList.tsx
- packages/uikit-react-native/src/domain/groupChannelSettings/component/GroupChannelSettingsMenu.tsx
- packages/uikit-react-native/src/domain/groupChannelThread/component/GroupChannelThreadMessageList.tsx
- packages/uikit-react-native/src/hooks/usePushTokenRegistration.ts
- packages/uikit-react-native/src/platform/createPlayerService.expo.tsx
- packages/uikit-react-native/src/platform/createPlayerService.native.tsx
- packages/uikit-react-native/src/platform/createRecorderService.native.tsx
- packages/uikit-utils/src/sendbird/channel.ts
- packages/uikit-utils/src/shared/bufferedRequest.ts
[CLNP-5191]
[CLNP-5191]: https://sendbird.atlassian.net/browse/CLNP-5191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLNP-5191] fix: added try/catch to unhandled errors

- packages/uikit-react-native/src/components/ChannelInput/SendInput.tsx
- packages/uikit-react-native/src/contexts/PlatformServiceCtx.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelThreadFragment.tsx
- packages/uikit-react-native/src/hooks/useConnection.ts
[TICKET_ID]
from https://github.com/sendbird/sendbird-uikit-react-native/pull/205
> chore: remove Promise.allSettled

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1440]
[SDKRLSD-1440]: https://sendbird.atlassian.net/browse/SDKRLSD-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1440] chore: release 3.7.4

- docs-validation/package.json
- package.json
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/domain/groupChannel/component/GroupChannelMessageList.tsx
- packages/uikit-react-native/src/domain/groupChannelThread/component/GroupChannelThreadMessageList.tsx
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/package.json
- sample/package.json
- yarn.lock
[AC-4084]
[AC-4084]: https://sendbird.atlassian.net/browse/AC-4084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AC-4084] feat: add scrolling for streaming message update

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
- Updated Android permissions to comply with Google Play Store policies
- Fixed an issue where images were not visible in the file viewer due to z-index conflicts in the new architecture
- Fixed an issue where reactions could not be added or removed correctly
- Fixed an issue with scroll behavior during message streaming in bot chats for smoother scrolling
> [SDKRLSD-1450] chore: release 3.7.5

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1452]
[SDKRLSD-1452]: https://sendbird.atlassian.net/browse/SDKRLSD-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1452] chore: release 3.7.6

- packages/uikit-react-native/src/components/ReactionAddons/MessageReactionAddon.tsx
- packages/uikit-react-native/src/components/ReactionAddons/ReactionRoundedButton.tsx
- packages/uikit-react-native/src/components/ReactionBottomSheets/ReactionUserListBottomSheet.tsx
- packages/uikit-react-native/src/libs/EmojiManager.ts
> fix: add emoji fallback icon

- packages/uikit-react-native/src/containers/SendbirdUIKitContainer.tsx
[CLNP-6034]
[CLNP-6034]: https://sendbird.atlassian.net/browse/CLNP-6034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLNP-6034] chore: enable overriding all chat options

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1495]
[SDKRLSD-1495]: https://sendbird.atlassian.net/browse/SDKRLSD-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1495] chore: release 3.8.2

- packages/uikit-react-native/package.json
[CLNP-6079]
Support mmkv@v3 (https://github.com/mrousavy/react-native-mmkv/releases)
[CLNP-6079]: https://sendbird.atlassian.net/browse/CLNP-6079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLNP-6079] chore: update mmkv version range

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1512](https://sendbird.atlassian.net/browse/SDKRLSD-1512)
update mmkv version range
[SDKRLSD-1512]: https://sendbird.atlassian.net/browse/SDKRLSD-1512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1512]  chore: release 3.8.3

- packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
- packages/uikit-react-native/src/fragments/createGroupChannelThreadFragment.tsx
[CLNP-6262](https://sendbird.atlassian.net/browse/CLNP-6262)
[CLNP-6262]: https://sendbird.atlassian.net/browse/CLNP-6262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLNP-6262] fix: remove duplicate MB text when uploading files over 25MB

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1530](https://sendbird.atlassian.net/browse/SDKRLSD-1530)
Fixed duplicate MB text appearing when uploading files over 25MB
[SDKRLSD-1530]: https://sendbird.atlassian.net/browse/SDKRLSD-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-] chore: release 3.8.4

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[[SDKRLSD-1536]](https://sendbird.atlassian.net/browse/SDKRLSD-1536)
Require only camera permission when using camera
[SDKRLSD-1536]: https://sendbird.atlassian.net/browse/SDKRLSD-1536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1536] chore: release 3.8.5

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[TICKET_ID]
[[SDKRLSD-1536]](https://sendbird.atlassian.net/browse/SDKRLSD-1536)
[SDKRLSD-1536]: https://sendbird.atlassian.net/browse/SDKRLSD-1536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1536] chore: release 3.8.6

- packages/uikit-react-native/src/components/ChatFlatList/FlatListInternal.tsx
[[CLNP-6534]](https://sendbird.atlassian.net/browse/CLNP-6534)
- Resolved FlatList-related error on Metro 0.81.3
- Both FlatListBidirectional and BidirectionalProps have been removed as they were unused.
[CLNP-6534]: https://sendbird.atlassian.net/browse/CLNP-6534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> [CLNP-6534] fix: resolve FlatList-related error on Metro 0.81.3

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[[SDKRLSD-1584]](https://sendbird.atlassian.net/browse/SDKRLSD-1584)
- add optional support for @react-native-documents/picker
- support for react-native 0.77 or later
- resolve FlatList-related error on Metro 0.81.3
[SDKRLSD-1584]: https://sendbird.atlassian.net/browse/SDKRLSD-1584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
> [SDKRLSD-1584] chore: release 3.9.0

- packages/uikit-react-native/package.json
- packages/uikit-react-native/src/platform/createFileService.expo.ts
- yarn.lock
[[CLNP-6592]](https://sendbird.atlassian.net/browse/CLNP-6592)
Bump minimum expo-media-library version for [Android policy compliance](https://support.google.com/googleplay/android-developer/answer/14115180)
Refactor permission handling for save
[CLNP-6592]: https://sendbird.atlassian.net/browse/CLNP-6592?atlOrigin=eyJpIjoiN …
> [CLNP-6592] refactor: bump minimum expo-media-library version for android policy compliance

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[[SDKRLSD-1585]](https://sendbird.atlassian.net/browse/SDKRLSD-1585)
- bump minimum expo-media-library version for android policy compliance
[CLNP-6592]: https://sendbird.atlassian.net/browse/CLNP-6592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDKRLSD-1585]: …
> [SDKRLSD-1585] release 3.9.1

- package.json
- packages/uikit-react-native/src/hooks/useMentionTextInput.ts
- packages/uikit-react-native/src/libs/MentionManager.tsx
- yarn.lock
[[CLNP-6663]](https://sendbird.atlassian.net/browse/CLNP-6663)
Added validation for the mentionedMessageTemplate API, as it was moved from BaseMessage to UserMessage in Chat SDK v4.16.4.
[CLNP-6663]: https://sendbird.atlassian.net/browse/CLNP-6663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> [CLNP-6663] fix: improve message validation related to mentionedMessageTemplate

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[[SDKRLSD-1588]](https://sendbird.atlassian.net/browse/SDKRLSD-1588)
- improve message validation related to mentionedMessageTemplate
[SDKRLSD-1588]: https://sendbird.atlassian.net/browse/SDKRLSD-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1588] release v3.9.2

- packages/uikit-react-native/package.json
- yarn.lock
[[CLNP-6702]](https://sendbird.atlassian.net/browse/CLNP-6702)
[CLNP-6702]: https://sendbird.atlassian.net/browse/CLNP-6702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLNP-6702] feat: update uikit-tools to 0.0.7 to support React Native 0.79

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[[SDKRLSD-1594]](https://sendbird.atlassian.net/browse/SDKRLSD-1594)
Update uikit-tools to 0.0.7 to support React Native 0.79
[SDKRLSD-1594]: https://sendbird.atlassian.net/browse/SDKRLSD-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1594] release v3.9.3

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[[SDKRLSD-1600]](https://sendbird.atlassian.net/browse/SDKRLSD-1600)
- allow string values for borderRadius in StyleSheet
[SDKRLSD-1600]: https://sendbird.atlassian.net/browse/SDKRLSD-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1600] release 3.9.4

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[[SDKRLSD-1620]](https://sendbird.atlassian.net/browse/SDKRLSD-1620)
- added flatListComponent to GroupChannelFragment to support custom FlatList in message list
[SDKRLSD-1620]: https://sendbird.atlassian.net/browse/SDKRLSD-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1620] release 3.9.5

- sample/ios/SendbirdUIKitSample.xcodeproj/project.pbxproj
> chore: update ios cert, profile

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[SDKRLSD-1708](https://sendbird.atlassian.net/browse/SDKRLSD-1708)
- add MarkAsUnread feature to GroupChannel
[SDKRLSD-1708]: https://sendbird.atlassian.net/browse/SDKRLSD-1708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1708] release 3.10.0

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[[SDKRLSD-1750]](https://sendbird.atlassian.net/browse/SDKRLSD-1750)
Features
- update @sendbird/uikit-tools to version 0.0.15(add react-native entry to package exports)
Bug Fixes
- improve keyboard avoidance behavior for Android API 35+
[SDKRLSD-1750]: https://sendbird.atlassian.net/browse/SDKRLSD-1750?atlOrigin=eyJpIjoiNWR …
> chore: update changelog for v3.10.1 release

- CHANGELOG.md
- CHANGELOG_DRAFT.md
- docs-validation/CHANGELOG.md
- docs-validation/package.json
- lerna.json
- packages/uikit-chat-hooks/CHANGELOG.md
- packages/uikit-chat-hooks/package.json
- packages/uikit-react-native-foundation/CHANGELOG.md
- packages/uikit-react-native-foundation/package.json
- packages/uikit-react-native/CHANGELOG.md
- packages/uikit-react-native/package.json
- packages/uikit-testing-tools/CHANGELOG.md
- packages/uikit-testing-tools/package.json
- packages/uikit-utils/CHANGELOG.md
- packages/uikit-utils/package.json
- sample/CHANGELOG.md
- sample/package.json
[[SDKRLSD-1762]](https://sendbird.atlassian.net/browse/SDKRLSD-1762)
[SDKRLSD-1762]: https://sendbird.atlassian.net/browse/SDKRLSD-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDKRLSD-1762] v3.10.3 release
